services:
  database:
    image: mysql
    container_name: "my-database"
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
  cache:
    image: "redis:7.4.0-alpine"
    container_name: "my-cache"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data:/var/lib/redis
